### ISSUE TITLE
Does not build recently (compiling rustc-serialize v0.3.19 fails: error[E0642]: patterns aren't allowed in methods without bodies)

### ISSUE THREAD

**Issue by mikken** [systemd-cron/systemd-cron-next#46] opened 2018-02-03 09:21 UTC
This is the error I encountered with rust 1.23:

```
>>> Compiling source in /var/tmp/portage/sys-process/systemd-crontab-generator-1.0.2/work/cargo_home/gentoo/systemd-crontab-generator-1.0.2 ...
make -j5 
make: Circular build <- all dependency dropped.
test -f /var/tmp/portage/sys-process/systemd-crontab-generator-1.0.2/work/cargo_home/gentoo/systemd-crontab-generator-1.0.2/out/build/bin/systemd-crontab-generator || \
    PREFIX="/usr" RUN_PARTS="/bin/run-parts" STATE_DIR="/var/spool/cron" \
    BIN_DIR="/usr/bin" CONF_DIR="/etc" MAN_DIR="/usr/share/man" DOC_DIR="/usr/share/doc/systemd-cron-next" \
    DATA_DIR="/usr/share" LIB_DIR="/usr/lib" UNIT_DIR="/lib/systemd/system" \
    cargo install --path /var/tmp/portage/sys-process/systemd-crontab-generator-1.0.2/work/cargo_home/gentoo/systemd-crontab-generator-1.0.2 --root /var/tmp/portage/sys-process/systemd-crontab-generator-1.0.2/work/cargo_home/gentoo/systemd-crontab-generator-1.0.2/out/build \
    --features "sched-hourly sched-daily sched-weekly sched-monthly persistent randomized-delay"
  Installing systemd-crontab-generator v1.0.2 (file:///var/tmp/portage/sys-process/systemd-crontab-generator-1.0.2/work/cargo_home/gentoo/systemd-crontab-generator-1.0.2)
   Compiling rustc-serialize v0.3.19
   Compiling log v0.3.6
   Compiling strsim v0.3.0
   Compiling num-traits v0.1.32
error[E0642]: patterns aren't allowed in methods without bodies
   --> /var/tmp/portage/sys-process/systemd-crontab-generator-1.0.2/work/cargo_home/gentoo/rustc-serialize-0.3.19/src/serialize.rs:147:45
    |
147 |                                             &f_name: &str,
    |                                             ^^^^^^^

   Compiling winapi-build v0.1.1
   Compiling regex-syntax v0.3.3
   Compiling libc v0.2.11
   Compiling utf8-ranges v0.1.3
   Compiling glob v0.2.11
error: aborting due to previous error

error: Could not compile `rustc-serialize`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `systemd-crontab-generator v1.0.2 (file:///var/tmp/portage/sys-process/systemd-crontab-generator-1.0.2/work/cargo_home/gentoo/systemd-crontab-generator-1.0.2)`, intermediate artifacts can be found at `/var/tmp/portage/sys-process/systemd-crontab-generator-1.0.2/work/cargo_home/gentoo/systemd-crontab-generator-1.0.2/target`
```

**Comment by KangarooCreativeTeam** [comment] 2018-06-18 22:51
I just got something similar;

```
   ...
   Compiling libc v0.1.12
   Compiling cronparse v0.5.0
   Compiling glob v0.2.11
error[E0642]: patterns aren't allowed in methods without bodies
   --> /home/kangaroo/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.19/src/serialize.rs:147:45
    |
147 |                                             &f_name: &str,
    |                                             ^^^^^^^

   Compiling md5 v0.1.1
   Compiling pgs-files v0.0.6
   Compiling kernel32-sys v0.2.2
   ...
   Compiling num-iter v0.1.32
   Compiling tempfile v1.1.3
error: aborting due to previous error

For more information about this error, try `rustc --explain E0642`.
error: Could not compile `rustc-serialize`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `systemd-crontab-generator v1.0.2 (file:///home/kangaroo/build/systemd-cron-next/src/systemd-cron-next-1.0.2)`, intermediate artifacts can be found at `/home/kangaroo/build/systemd-cron-next/src/systemd-cron-next-1.0.2/target`

Caused by:
  build failed
make: *** [Makefile:67: build] Error 101
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by kstep** [comment] 2018-10-30 13:53
@mikken I merged the PR. Please check if the issue is fixed and close it if all's OK.

**Comment by agrover** [comment] 2020-05-17 04:43
This should be closed.

**Closed** 2020-06-14 08:58 UTC
